language: python
python:
  - 3.6
before_install:
  - sudo apt-get install python-enchant
install:
  - pip install -r requirements.txt
  - pip install -r requirements-optional.txt
script:
  - pre-commit clean
  - pre-commit run --all-files
  - make docs-html
after_failure:
  - git diff
