# CI stages to execute against Pull Requests
name: Airgun - CI

on:
  pull_request:
    types: ["opened", "synchronize", "reopened"]

env:
    PYCURL_SSL_LIBRARY: openssl
    UV_SYSTEM_PYTHON: 1

jobs:
  codechecks:
    name: Code Quality
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
    steps:
      - name: Checkout Airgun
        uses: actions/checkout@v4

      - name: Set Up Python-${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the latest version of uv and set the Python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          cache-dependency-glob: |
            **/requirements*.txt
            **/setup.py

      - name: Install Dependencies
        run: |
          sudo apt update
          uv pip install -U -r requirements.txt -r requirements-optional.txt

      - name: Analysis (git diff)
        if: failure()
        run: git diff

      - name: Docs Build
        run: |
         make docs-html

  robottelo-cross-check:
    name: Robottelo installation cross-check
    runs-on: ubuntu-latest
    needs: codechecks
    steps:
      - name: Checkout Airgun
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install the latest version of uv and set the Python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.12'
          enable-cache: true
          cache-dependency-glob: |
            **/requirements*.txt
            **/setup.py

      - name: Download robottelo's requirements.txt
        run: |
          curl -s https://raw.githubusercontent.com/SatelliteQE/robottelo/$GITHUB_BASE_REF/requirements.txt -o requirements-robottelo.txt

      - name: Remove airgun from robottelo requirements
        run: |
          sed -i '/airgun/d' requirements-robottelo.txt

      - name: Robottelo Installability
        run: |
          uv pip install -U -r requirements-robottelo.txt -r requirements.txt -r requirements-optional.txt
